Fix pixelart style and add better FEN checking

diff --git a/fen2svg b/fen2svg
--- a/fen2svg
+++ b/fen2svg
@@ -24,6 +24,44 @@ usage() {
     exit 1
 }
 
+# The chkfen function checks the FEN piece placement string for validity, including each rank having
+# 8 squares, there being 8 ranks, and the pieces being valid. It does not check the number of
+# pieces, or the presence of pawns in rank 1 and 8. The function an exit status of 0 if valid, or an
+# exit status of 1 if invalid.
+chkfen() {
+    local fen="$1/" # Add a trailing slash to the FEN string to make it easier to parse
+
+    # Check for valid basic FEN format.
+    if [[ ! "$fen" =~ ^([pnbrqkPNBRQK1-8]{1,8}/){8}$ ]] ; then
+        return 1
+    fi
+
+    # Iterate over the string, keeping count of the number of occurrences of each piece using
+    #  arrays. While iterating, keep track of the number of squares in each rank. When reaching a
+    # slash or the end of the string, check that the number of squares in the rank is 8.
+    local rank_squares=0
+    for ((i = 0; i < ${#fen}; ++i)); do
+        char=${fen:i:1}
+        case $char in
+            [1-8]) # Number of empty squares
+                ((rank_squares += char))
+                ;;
+            /) # End of rank
+                ((rank_count++))
+                if ((rank_squares != 8)); then
+                    echo "Invalid rank ${rank_count}: $rank_squares squares" >&2
+                    return 1
+                fi
+                rank_squares=0
+                ;;
+            *) # Piece
+                ((rank_squares++))
+                ;;
+        esac
+    done
+    return 0
+}
+
 # Process the command line options
 while getopts "d:g:lo:s:tux" opt ; do
     case $opt in
@@ -52,10 +90,15 @@ shift $((OPTIND - 1))
 
 # This script takes a chess FEN piece placement and outputs an SVG file that shows
 # the chessboard with that setup.
-if [ $# -lt 1 ] ; then
+if [ $# -lt 1 -o "$1" = "startpos" ] ; then
     fen="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"
 else
     fen=$1
+fi
+fen="${fen//_/1}" # allow _ to stand for no piece
+if ! chkfen "$fen" ; then
+    echo "Invalid FEN piece placement: \"$fen\"" >&2
+    exit 2
 fi
 
 if [[ ! ("$fen" =~ ^([rnbqkpRNBQKP1-8]{1,8}/){7}[rnbqkpRNBQKP1-8]{1,8}$) ]] ; then
